### ISSUE TITLE
Horario de evaluación de última instancia

### ISSUE THREAD

**Issue by tcouso** [IIC2233/syllabus-2020-1#1369]
Hola!

Según entendí por los issues anteriores, mañana lunes 20 de julio será la evaluación de última instancia del ramo, pero me queda pendiente el tema de los horarios ¿Será con asignación de un horario para cada estudiante? Quedo atento a cualquier información.

Saludos y gracias de antemano!

**Comment by fdoflorenzano** [comment]
Hola @tcouso,

Anunciaremos esta información lo antes posible. Pero sí, será con asignación de horario por estudiante. Se le mandará durante el día un correo para hacerlo a aquellas personas que pueden optar por evaluación de última instancia.

Saludos.

**Comment by tcouso** [comment]
Ok, muchas gracias por la información!
